
/*
    Autores:
    Mateo Franciulli 310956
    Ivan Castelli 306188
 */

package interfaz;
import dominio.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;

public class VentanaMenuInicio extends javax.swing.JFrame {
    private Modelo modelo;
    
    public VentanaMenuInicio() throws IOException {
         modelo = new Modelo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntSistemaAnterior = new javax.swing.JButton();
        btnSistemaNuevo = new javax.swing.JButton();
        lblMenuInicio2 = new javax.swing.JLabel();
        lblMenuInicio1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntSistemaAnterior.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntSistemaAnterior.setText("Sistema anterior");
        bntSistemaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSistemaAnteriorActionPerformed(evt);
            }
        });

        btnSistemaNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSistemaNuevo.setText("Sistema nuevo");
        btnSistemaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaNuevoActionPerformed(evt);
            }
        });

        lblMenuInicio2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMenuInicio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuInicio2.setText("BIENVENIDO!");

        lblMenuInicio1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMenuInicio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuInicio1.setText("SELECCIONE SISTEMA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnSistemaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(bntSistemaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lblMenuInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblMenuInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMenuInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSistemaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSistemaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSistemaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaNuevoActionPerformed
  try {
        //Borrar el sistema que existe, si existe
        File sistemaFile = new File("sistema");
        if (sistemaFile.exists()) {
            sistemaFile.delete();
        }

        
        Modelo modelo = new Modelo();
        modelo.guardarDatos(); //Creo nuevo sistema
        VentanaMenu vent = new VentanaMenu(modelo);
        vent.setVisible(true);
        this.dispose();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al iniciar el nuevo sistema!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSistemaNuevoActionPerformed

    private void bntSistemaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSistemaAnteriorActionPerformed
try (FileInputStream ar = new FileInputStream("sistema")) {
            ObjectInputStream leer = new ObjectInputStream(ar);
            modelo = (Modelo) leer.readObject();
            JOptionPane.showMessageDialog(null, "Sistema Recibido!", "Correcto", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "No existe un Sistema anterior o error al leer Archivo!, Se inicia con nuevo sistema", "Error", JOptionPane.ERROR_MESSAGE);
            modelo = new Modelo();
        }
        VentanaMenu vent = new VentanaMenu(modelo);
        vent.setVisible(true);
        this.dispose();
  
    }//GEN-LAST:event_bntSistemaAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSistemaAnterior;
    private javax.swing.JButton btnSistemaNuevo;
    private javax.swing.JLabel lblMenuInicio1;
    private javax.swing.JLabel lblMenuInicio2;
    // End of variables declaration//GEN-END:variables
}
