/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author Usuario
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmbBarraMenu = new javax.swing.JMenuBar();
        jmRegistro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmRegistrarVenta = new javax.swing.JMenuItem();
        jmAnularVenta = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmConsultaVentas = new javax.swing.JMenuItem();
        jmConsultaLibros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de librerías - Realizado por: Mateo Franciulli 310956, Iván Castelli 306188");

        jmRegistro.setText("Registros");
        jmRegistro.setActionCommand("Registro");

        jMenuItem1.setText("Registro Editorial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmRegistro.add(jMenuItem1);

        jMenuItem2.setText("Registro Género");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmRegistro.add(jMenuItem2);

        jMenuItem3.setText("Registro Autor");
        jmRegistro.add(jMenuItem3);

        jMenuItem4.setText("Registro Libro");
        jmRegistro.add(jMenuItem4);

        jmbBarraMenu.add(jmRegistro);

        jMenu5.setText("Ventas");

        jmRegistrarVenta.setText("Registrar Venta");
        jMenu5.add(jmRegistrarVenta);

        jmAnularVenta.setText("Anular Venta");
        jMenu5.add(jmAnularVenta);

        jmbBarraMenu.add(jMenu5);

        jMenu6.setText("Consultas");

        jmConsultaVentas.setText("Consulta de Ventas");
        jMenu6.add(jmConsultaVentas);

        jmConsultaLibros.setText("Consulta de Libros");
        jMenu6.add(jmConsultaLibros);

        jmbBarraMenu.add(jMenu6);

        setJMenuBar(jmbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jmAnularVenta;
    private javax.swing.JMenuItem jmConsultaLibros;
    private javax.swing.JMenuItem jmConsultaVentas;
    private javax.swing.JMenuItem jmRegistrarVenta;
    private javax.swing.JMenu jmRegistro;
    private javax.swing.JMenuBar jmbBarraMenu;
    // End of variables declaration//GEN-END:variables
}
