/*
    Autores:
    Mateo Franciulli 310956
    Ivan Castelli 306188
 */

package interfaz;

import dominio.Genero;
import dominio.Modelo;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class VentanaRegistroGenero extends javax.swing.JFrame implements Observer {
    
   
    private DefaultListModel<String> liGenerosRegistradosModel = new DefaultListModel<>();
    private DefaultListModel<String> liDescGeneroRegistradoModel = new DefaultListModel<>();
    private Modelo modelo; // creo modelo global
        
    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistroGenero(Modelo modelo) {
        this.modelo = modelo;
        initComponents();
        liGenerosRegistrados.setModel(liGenerosRegistradosModel); // asigna el modelo a la Jlist para luego usar addElement 
        liDescGeneroRegistrado.setModel(liDescGeneroRegistradoModel);
        cargarGeneros();
        modelo.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistroGenero = new javax.swing.JLabel();
        lblNombreGenero = new javax.swing.JLabel();
        lblDescripcionGenero = new javax.swing.JLabel();
        txtNombreGenero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        liGenerosRegistrados = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        liDescGeneroRegistrado = new javax.swing.JList<>();
        lblGenerosRegistrados = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        jbIngresarGenero = new javax.swing.JButton();

        setTitle("Registro de género");

        lblRegistroGenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRegistroGenero.setText("Registro de género");
        lblRegistroGenero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblNombreGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreGenero.setText("Nombre del género :");
        lblNombreGenero.setFocusable(false);

        lblDescripcionGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionGenero.setText("Descripción :");
        lblDescripcionGenero.setFocusable(false);

        txtNombreGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreGeneroActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(liGenerosRegistrados);

        jScrollPane2.setViewportView(liDescGeneroRegistrado);

        lblGenerosRegistrados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGenerosRegistrados.setText("Géneros registrados :");
        lblGenerosRegistrados.setFocusable(false);

        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtAreaDescripcion);

        jbIngresarGenero.setText("Ingresar");
        jbIngresarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarGeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcionGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenerosRegistrados))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblRegistroGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62)
                        .addComponent(jbIngresarGenero)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRegistroGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDescripcionGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbIngresarGenero)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenerosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     private void cargarGeneros() {
        liGenerosRegistradosModel.clear();
        liDescGeneroRegistradoModel.clear();
        for (Genero genero : modelo.getGeneros()) {
            liGenerosRegistradosModel.addElement(genero.getNombre());
            liDescGeneroRegistradoModel.addElement(genero.getDescripcion());
        }
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof Genero) {
            Genero genero = (Genero) arg;
            liGenerosRegistradosModel.addElement(genero.getNombre());
            liDescGeneroRegistradoModel.addElement(genero.getDescripcion());
        }
    }
    private void txtNombreGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGeneroActionPerformed

    private void jbIngresarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarGeneroActionPerformed
        String nombre = this.txtNombreGenero.getText();
        String descripcion = this.txtAreaDescripcion.getText();

        if (!modelo.verificoGeneros(nombre)) {
            JOptionPane.showMessageDialog(null, "Nombre ya registrado, por favor registre uno válido.");
        }else// Validación para asegurarse de que solo se ingresen letras
            if (!nombre.matches("[a-zA-Z ]+")||!descripcion.matches("[a-zA-Z ]+")) { // esta validacion fue hecha con ayuda de chat GPT (link:https://chatgpt.com/share/66fb3ee0-30e0-800d-a8cb-438856f220ca)
                JOptionPane.showMessageDialog(null,"Los datos solo admiten letras, ingrese datos válidos");
        }else 
        
            if(nombre.length()<2||descripcion.length()<2){
                JOptionPane.showMessageDialog(null, "Complete todos los campos.");
        } else {
            Genero genero = new Genero(nombre, descripcion); // objeto genero
            modelo.agregarGenero(genero); // aniado el genero a la lista            
            //liGenerosRegistradosModel.addElement(nombre); // aniado el nombre al modelo de la lista
            //liDescGeneroRegistradoModel.addElement(descripcion); // aniado la desc. al modelo de la lista
            cargarGeneros();
            JOptionPane.showMessageDialog(null, "Nuevo Género ingresado:\n" + genero);
        }

        // vacío campos
        txtNombreGenero.setText("");
        txtAreaDescripcion.setText("");  
    }//GEN-LAST:event_jbIngresarGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbIngresarGenero;
    private javax.swing.JLabel lblDescripcionGenero;
    private javax.swing.JLabel lblGenerosRegistrados;
    private javax.swing.JLabel lblNombreGenero;
    private javax.swing.JLabel lblRegistroGenero;
    private javax.swing.JList<String> liDescGeneroRegistrado;
    private javax.swing.JList<String> liGenerosRegistrados;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtNombreGenero;
    // End of variables declaration//GEN-END:variables
}
