/*
    Autores:
    Mateo Franciulli 310956
    Ivan Castelli 306188
 */

package interfaz;

import dominio.ArchivoGrabacion;
import dominio.Libro;
import dominio.Modelo;
import dominio.Ventas;
import static java.lang.Integer.parseInt;


public class VentanaConsultaVentas extends javax.swing.JFrame {
    Modelo modelo;
    /**
     * Creates new form VentanaConsultaVentas
     */
    public VentanaConsultaVentas(Modelo modelo) {
        this.modelo=modelo;
        initComponents();
        jList1.setVisible(false);
        
       jList1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jList1MouseClicked(evt);
        }
    });
    }
    
    
    String fecha;
    String cliente;
    String factura;
    String cantidad;
    String precioVenta;
    String precioCosto;
    String importe;
    int ejemplares=0;
    int recaudado=0;
    int ganancias=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        btnPanelAux = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblRecaudado = new javax.swing.JLabel();
        lbEVendidos = new javax.swing.JLabel();
        lblGanancias = new javax.swing.JLabel();
        jlAyuda = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setTitle("Consulta de Ventas");

        jLabel1.setText("Isbn");

        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });

        btnPanelAux.setText("...");
        btnPanelAux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelAuxActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        labelTitulo.setText(" ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Cliente", "Factura", "Cantidad", "Precio", "Importe"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPanelAux)
                        .addGap(66, 66, 66)
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanelAux)
                    .addComponent(btnConsultar)
                    .addComponent(btnExportar))
                .addGap(18, 18, 18)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText("Ejemplares vendidos");

        jLabel3.setText("Total recaudado");

        jLabel4.setText("Total Ganancias");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlAyuda.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEVendidos)
                        .addGap(170, 170, 170)
                        .addComponent(lblRecaudado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lblGanancias))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jlAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecaudado)
                    .addComponent(lblGanancias)
                    .addComponent(lbEVendidos))
                .addGap(0, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void btnPanelAuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelAuxActionPerformed
     jList1.setVisible(true);

    
    java.util.List<Libro> librosDisponibles = modelo.getLibros(); 

    // Crea un array con los tiutlos de los libros
    String[] nombresLibros = new String[librosDisponibles.size()];
    for (int i = 0; i < librosDisponibles.size(); i++) {
        nombresLibros[i] = librosDisponibles.get(i).getIsbn();
    }

    
    jList1.setListData(nombresLibros);
    }//GEN-LAST:event_btnPanelAuxActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
    String isbn = txtIsbn.getText();
    
    javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) jTable1.getModel();        
    tableModel.setRowCount(0);    
    java.util.List<String[]> datos = obtenerDatosPorIsbn(isbn); 
        
    for (String[] fila : datos) {
        tableModel.addRow(fila);        
    }
    
    lbEVendidos.setText(String.valueOf(ejemplares));
    lblRecaudado.setText(String.valueOf(recaudado));
    lblGanancias.setText(String.valueOf(ganancias));
    //color
    lbEVendidos.setForeground(java.awt.Color.BLUE);
    lblRecaudado.setForeground(java.awt.Color.BLUE);
    lblGanancias.setForeground(java.awt.Color.BLUE);
}

    private java.util.List<String[]> obtenerDatosPorIsbn(String isbn) {
    java.util.List<String[]> datos = new java.util.ArrayList<>();
    for (Ventas ventas : modelo.ventas) {
        for (Libro ventasLib : ventas.getLibrosVendidos()) {
            if (ventasLib.getIsbn().equalsIgnoreCase(isbn)) {
                String fecha = ventas.getFecha();
                String cliente = ventas.getCliente();
                
                String factura = ventas.getFactura() + "";
                String cantidad = String.valueOf(ventasLib.getCantidadVendidoEnVenta());
                String precioVenta = ventasLib.getPrecioVenta() + "";
                String precioCosto = ventasLib.getPrecioCosto() + "";
                
                ejemplares += Integer.parseInt(cantidad);
                String importe = String.valueOf((int) (Integer.parseInt(cantidad) * Double.parseDouble(precioVenta)));
                System.out.println("importe: " + importe);
                recaudado += Integer.parseInt(importe);
                ganancias += (Double.parseDouble(precioVenta) - Double.parseDouble(precioCosto)) * Integer.parseInt(cantidad);
                
                datos.add(new String[]{fecha, cliente, factura, cantidad, precioVenta, importe});
                importe = "";
                cantidad = "";
            }
        }
    }
    System.out.println(ejemplares);
    System.out.println(recaudado);
    System.out.println(ganancias);
    return datos;
    }//GEN-LAST:event_btnConsultarActionPerformed

    
    private void exportarDatos() {
    ArchivoGrabacion archivo = new ArchivoGrabacion("VENTAS.CSV");

    // Escribir los títulos de las columnas
    archivo.grabarLinea("Fecha;Cliente;Factura;Cantidad;Precio;Importe");

    // Obtener el modelo de la tabla y escribir los datos
    javax.swing.table.TableModel modeloTabla = jTable1.getModel();
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        StringBuilder linea = new StringBuilder();
        for (int j = 0; j < modeloTabla.getColumnCount(); j++) {
            linea.append(modeloTabla.getValueAt(i, j).toString());
            if (j < modeloTabla.getColumnCount() - 1) {
                linea.append(";");
            }
        }
        archivo.grabarLinea(linea.toString());
    }
    archivo.cerrar();
}
    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        exportarDatos();
    }//GEN-LAST:event_btnExportarActionPerformed

    
    
    
    private String obtenerIsbnPorNombre(String nombreLibro) {
    for (Libro libro : modelo.getLibros()) {
        if (libro.getIsbn().equals(nombreLibro)) {
            return libro.getIsbn();
        }
    }
    return null;
}
    private void consultarLibro(String isbn) {
    
    javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    tableModel.setRowCount(0);
    java.util.List<String[]> datos = obtenerDatosPorIsbn(isbn); 

    // agrega filas a la tabla
    for (String[] fila : datos) {
        tableModel.addRow(fila);
    }

    lbEVendidos.setText(String.valueOf(ejemplares));
    lblRecaudado.setText(String.valueOf(recaudado));
    lblGanancias.setText(String.valueOf(ganancias));

    lbEVendidos.setForeground(java.awt.Color.BLUE);
    lblRecaudado.setForeground(java.awt.Color.BLUE);
    lblGanancias.setForeground(java.awt.Color.BLUE);
}
    
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {
    // Verificar si se hizo doble clic en un elemento
    if (evt.getClickCount() == 2) {
        String nombreLibroSeleccionado = jList1.getSelectedValue();
        if (nombreLibroSeleccionado != null) {
            
            String isbnSeleccionado = obtenerIsbnPorNombre(nombreLibroSeleccionado);            
            consultarLibro(isbnSeleccionado);            
            jList1.setVisible(false);
        }
    }
}
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnPanelAux;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jlAyuda;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel lbEVendidos;
    private javax.swing.JLabel lblGanancias;
    private javax.swing.JLabel lblRecaudado;
    private javax.swing.JTextField txtIsbn;
    // End of variables declaration//GEN-END:variables
}
